config/routes.rb
Rails.application.routes.draw do
  resources :consultas
  resources :medicos
  resources :pacientes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/paciente.rb
require "cpf_cnpj"

class Paciente < ApplicationRecord

  has_one :endereco, dependent: :destroy
  accepts_nested_attributes_for :endereco, allow_destroy: true
  has_many :consultums
  has_many :medicos, through: :consultums

  validates :nome, presence: true, length: {in: 5..40}
  validate :data_nascimento_valida
  validate :cpf_valido
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  def data_nascimento_valida
    if data_nascimento.present? && data_nascimento > Date.today
      errors.add(:data, "nao pode ser no futuro")
    end
  end

  def cpf_valido
    if cpf.present? && !CPF.valid?(cpf)
      errors.add(:cpf, "formato ou numero errado")
    end
  end
end

app/controllers/pacientes_controller.rb
class PacientesController < ApplicationController
  before_action :set_paciente, only: %i[ show edit update destroy ]

  # GET /pacientes or /pacientes.json
  def index
    @pacientes = Paciente.all
  end

  # GET /pacientes/1 or /pacientes/1.json
  def show
  end

  # GET /pacientes/new
  def new
    @paciente = Paciente.new
    @paciente.build_endereco
  end

  # GET /pacientes/1/edit
  def edit
  end

  # POST /pacientes or /pacientes.json
  def create
    @paciente = Paciente.new(paciente_params)
    @paciente.endereco = Endereco.new(paciente_params[:endereco_attributes])

    respond_to do |format|
      if @paciente.save
        format.html { redirect_to paciente_url(@paciente), notice: "Paciente was successfully created." }
        format.json { render :show, status: :created, location: @paciente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pacientes/1 or /pacientes/1.json
  def update
    respond_to do |format|
      if @paciente.update(paciente_params)
        format.html { redirect_to paciente_url(@paciente), notice: "Paciente was successfully updated." }
        format.json { render :show, status: :ok, location: @paciente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pacientes/1 or /pacientes/1.json
  def destroy
    @paciente.destroy

    respond_to do |format|
      format.html { redirect_to pacientes_url, notice: "Paciente was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paciente
      @paciente = Paciente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def paciente_params
      params.require(:paciente).permit(:nome, :data_nascimento, :cpf, :email,
                                       endereco_attributes: [:logradouro, :complemento, :cep, :bairro, :cidade])
    end
end

app/helpers/pacientes_helper.rb
module PacientesHelper
end

app/views/pacientes/_form.html.erb
<%= form_with(model: paciente) do |form| %>
  <% if paciente.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(paciente.errors.count, "error") %> prohibited this paciente from being saved:</h2>

      <ul>
        <% paciente.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :data_nascimento, style: "display: block" %>
    <%= form.date_field :data_nascimento %>
  </div>

  <div>
    <%= form.label :cpf, style: "display: block" %>
    <%= form.text_field :cpf %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <%= form.fields_for :endereco do |endereco_form| %>

    <div class="field">
      <%= endereco_form.label :logradouro %>
      <%= endereco_form.text_field :logradouro %>
    </div>

    <div class="field">
      <%= endereco_form.label :complemento %>
      <%= endereco_form.text_field :complemento %>
    </div>

    <div class="field">
      <%= endereco_form.label :cep %>
      <%= endereco_form.text_field :cep %>
    </div>

    <div class="field">
      <%= endereco_form.label :bairro %>
      <%= endereco_form.text_field :bairro %>
    </div>

    <div class="field">
      <%= endereco_form.label :cidade %>
      <%= endereco_form.text_field :cidade %>
    </div>

  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pacientes/_paciente.html.erb
<div id="<%= dom_id paciente %>">
  <p>
    <strong>Nome:</strong>
    <%= paciente.nome %>
  </p>

  <p>
    <strong>Data nascimento:</strong>
    <%= paciente.data_nascimento %>
  </p>

  <p>
    <strong>Cpf:</strong>
    <%= paciente.cpf %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= paciente.email %>
  </p>

  <p>
    <strong>Logradouro:</strong>
    <%= paciente.endereco.logradouro %>
  </p>

  <p>
    <strong>Complemento:</strong>
    <%= paciente.endereco.complemento %>
  </p>

  <p>
    <strong>CEP:</strong>
    <%= paciente.endereco.cep %>
  </p>

  <p>
    <strong>Bairro:</strong>
    <%= paciente.endereco.bairro %>
  </p>

  <p>
    <strong>Cidade:</strong>
    <%= paciente.endereco.cidade %>
  </p>

</div>

app/views/pacientes/edit.html.erb
<h1>Editing paciente</h1>

<%= render "form", paciente: @paciente %>

<br>

<div>
  <%= link_to "Show this paciente", @paciente %> |
  <%= link_to "Back to pacientes", pacientes_path %>
</div>

app/views/pacientes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pacientes</h1>

<div id="pacientes">
  <% @pacientes.each do |paciente| %>
    <%= render paciente %>
    <p>
      <%= link_to "Show this paciente", paciente %>
    </p>
  <% end %>
</div>

<%= link_to "New paciente", new_paciente_path %>

app/views/pacientes/new.html.erb
<h1>New paciente</h1>

<%= render "form", paciente: @paciente %>

<br>

<div>
  <%= link_to "Back to pacientes", pacientes_path %>
</div>

app/views/pacientes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @paciente %>

<div>
  <%= link_to "Edit this paciente", edit_paciente_path(@paciente) %> |
  <%= link_to "Back to pacientes", pacientes_path %>

  <%= button_to "Destroy this paciente", @paciente, method: :delete %>
</div>