config/routes.rb
Rails.application.routes.draw do
  resources :consultas
  resources :medicos
  resources :pacientes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/consulta.rb
class Consulta < ApplicationRecord

  belongs_to :medico
  belongs_to :paciente

  validate :data_consulta_futuro
  validate :horarios_validos

  def data_consulta_futuro
    if data.present? && data < Date.today
      errors.add(:data, "nao pode ser no passado")
    end
  end

  def horarios_validos
    if %w[08:00 09:00 10:00 11:00 14:00 15:00 16:00 17:00].exclude? horario
      errors.add(:horario, "horario invalido")
    end
  end
end

app/controllers/consultas_controller.rb
class ConsultasController < ApplicationController
  before_action :set_consulta, only: %i[ show edit update destroy ]

  # GET /consultas or /consultas.json
  def index
    @consultas = Consulta.all
  end

  # GET /consultas/1 or /consultas/1.json
  def show
  end

  # GET /consultas/new
  def new
    @consulta = Consulta.new
  end

  # GET /consultas/1/edit
  def edit
  end

  # POST /consultas or /consultas.json
  def create
    @medico = Medico.find(consulta_params[:medico_id])
    @paciente = Paciente.find(consulta_params[:paciente_id])
    @consulta = Consulta.new(consulta_params)
    @medico.consultas << @consulta
    @paciente.consultas << @consulta

    respond_to do |format|
      if @consulta.save
        format.html { redirect_to consulta_url(@consulta), notice: "Consulta was successfully created." }
        format.json { render :show, status: :created, location: @consulta }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @consulta.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consultas/1 or /consultas/1.json
  def update
    respond_to do |format|
      if @consulta.update(consulta_params)
        format.html { redirect_to consulta_url(@consulta), notice: "Consulta was successfully updated." }
        format.json { render :show, status: :ok, location: @consulta }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @consulta.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consultas/1 or /consultas/1.json
  def destroy
    @consulta.destroy

    respond_to do |format|
      format.html { redirect_to consultas_url, notice: "Consulta was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consulta
      @consulta = Consulta.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def consulta_params
      params.require(:consulta).permit(:data, :horario, :medico_id, :paciente_id)
    end
end

app/helpers/consultas_helper.rb
module ConsultasHelper
end

app/views/consultas/_consulta.html.erb
<div id="<%= dom_id consulta %>">
  <p>
    <strong>Data:</strong>
    <%= consulta.data %>
  </p>

  <p>
    <strong>Horario:</strong>
    <%= consulta.horario %>
  </p>

  <p>
    <strong>Medico:</strong>
    <%= Medico.find(consulta.medico_id).nome %>
  </p>

  <p>
    <strong>Paciente:</strong>
    <%= Paciente.find(consulta.paciente_id).nome %>
  </p>

</div>

app/views/consultas/_form.html.erb
<%= form_with(model: consulta) do |form| %>
  <% if consulta.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(consulta.errors.count, "error") %> prohibited this consulta from being saved:</h2>

      <ul>
        <% consulta.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :data, style: "display: block" %>
    <%= form.date_field :data %>
  </div>

  <div>
    <%= form.label :horario, style: "display: block" %>
    <%= form.select(:horario, %w[08:00 09:00 10:00 11:00 14:00 15:00 16:00 17:00])%>
  </div>

  <div class="field">
    <%= form.label :medico_id %>
    <%= form.collection_select(:medico_id, Medico.all, :id, :nome,{:selected => @consulta.medico_id})%>
  </div>

  <div class="field">
    <%= form.label :paciente_id %>
    <%= form.collection_select(:paciente_id, Paciente.all, :id, :nome,{:selected => @consulta.paciente_id})%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/consultas/edit.html.erb
<h1>Editing consulta</h1>

<%= render "form", consulta: @consulta %>

<br>

<div>
  <%= link_to "Show this consulta", @consulta %> |
  <%= link_to "Back to consultas", consultas_path %>
</div>

app/views/consultas/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Consultas</h1>

<div id="consultas">
  <% @consultas.each do |consulta| %>
    <%= render consulta %>
    <p>
      <%= link_to "Show this consulta", consulta %>
    </p>
  <% end %>
</div>

<%= link_to "New consulta", new_consulta_path %>

app/views/consultas/new.html.erb
<h1>New consulta</h1>

<%= render "form", consulta: @consulta %>

<br>

<div>
  <%= link_to "Back to consultas", consultas_path %>
</div>

app/views/consultas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @consulta %>

<div>
  <%= link_to "Edit this consulta", edit_consulta_path(@consulta) %> |
  <%= link_to "Back to consultas", consultas_path %>

  <%= button_to "Destroy this consulta", @consulta, method: :delete %>
</div>